### ISSUE TITLE
Error while trying to run workflow on kubernetes cluster.

### ISSUE THREAD

**Issue by Vin-itall** [mlrun/mlrun#711]
> @narendra36 you should set both `DEFAULT_DOCKER_REGISTRY` (url, e.g. `https://index.docker.io/v1/`) and `DEFAULT_DOCKER_SECRET` (k8s secret name, in the same namespace), another way is to set the registry per function, add this method to your function object `fn.build_config(image='target/image:tag', secret='my_docker')`

I have these set but I am still facing this issue.

![Screenshot 2021-02-05 at 10 02 31 AM](https://user-images.githubusercontent.com/12558361/107064952-665d9b80-6799-11eb-92ee-ca52a39ad7f7.png)

`kubectl logs demo-training-pipeline-bn97r-3933567025 -n kubeflow wait`
```
time="2021-02-05T16:43:48Z" level=info msg="Starting Workflow Executor" version=v2.7.5+ede163e.dirty
time="2021-02-05T16:43:49Z" level=info msg="Creating PNS executor (namespace: kubeflow, pod: demo-training-pipeline-bn97r-3933567025, pid: 6, hasOutputs: true)"
time="2021-02-05T16:43:49Z" level=info msg="Executor (version: v2.7.5+ede163e.dirty, build_date: 2020-04-21T01:12:08Z) initialized (pod: kubeflow/demo-training-pipeline-bn97r-3933567025) with template:\n{\"name\":\"deploy-gen-iris\",\"arguments\":{},\"inputs\":{},\"outputs\":{\"parameters\":[{\"name\":\"deploy-gen-iris-image\",\"valueFrom\":{\"path\":\"/tmp/image\"}}],\"artifacts\":[{\"name\":\"deploy-gen-iris-image\",\"path\":\"/tmp/image\"},{\"name\":\"deploy-gen-iris-state\",\"path\":\"/tmp/state\"}]},\"metadata\":{\"annotations\":{\"sidecar.istio.io/inject\":\"false\"},\"labels\":{\"pipelines.kubeflow.org/cache_enabled\":\"true\"}},\"container\":{\"name\":\"\",\"image\":\"mlrun/mlrun:0.5.5-rc3\",\"command\":[\"python\",\"-m\",\"mlrun\",\"build\",\"--kfp\",\"-r\",\"{'kind': 'job', 'metadata': {'name': 'gen-iris', 'tag': '', 'project': 'sk-project'}, 'spec': {'command': '', 'args': [], 'volumes': [{'name': 'pvc-55208e8c-6cf1-483f-a107-bea804c96384', 'persistentVolumeClaim': {'claimName': 'mlrun-kit-jupyter-pvc'}}], 'volume_mounts': [{'mountPath': '/home/jovyan/data', 'name': 'pvc-55208e8c-6cf1-483f-a107-bea804c96384'}], 'env': [], 'default_handler': '', 'entry_points': {'iris_generator': {'name': 'iris_generator', 'doc': '', 'parameters': [{'name': 'context', 'default': ''}, {'name': 'format', 'default': 'csv'}], 'outputs': [{'default': ''}], 'lineno': 11}}, 'description': '', 'build': {'functionSourceCode': 'IyBHZW5lcmF0ZWQgYnkgbnVjbGlvLmV4cG9ydC5OdWNsaW9FeHBvcnRlcgoKaW1wb3J0IG9zCmZyb20gc2tsZWFybi5kYXRhc2V0cyBpbXBvcnQgbG9hZF9pcmlzCmZyb20gc2tsZWFybi5tb2RlbF9zZWxlY3Rpb24gaW1wb3J0IHRyYWluX3Rlc3Rfc3BsaXQKaW1wb3J0IG51bXB5IGFzIG5wCmZyb20gc2tsZWFybi5tZXRyaWNzIGltcG9ydCBhY2N1cmFjeV9zY29yZQpmcm9tIG1scnVuLmFydGlmYWN0cyBpbXBvcnQgVGFibGVBcnRpZmFjdCwgUGxvdEFydGlmYWN0CmltcG9ydCBwYW5kYXMgYXMgcGQKCmRlZiBpcmlzX2dlbmVyYXRvcihjb250ZXh0LCBmb3JtYXQ9J2NzdicpOgogICAgaXJpcyA9IGxvYWRfaXJpcygpCiAgICBpcmlzX2RhdGFzZXQgPSBwZC5EYXRhRnJhbWUoZGF0YT1pcmlzLmRhdGEsIGNvbHVtbnM9aXJpcy5mZWF0dXJlX25hbWVzKQogICAgaXJpc19sYWJlbHMgPSBwZC5EYXRhRnJhbWUoZGF0YT1pcmlzLnRhcmdldCwgY29sdW1ucz1bJ2xhYmVsJ10pCiAgICBpcmlzX2RhdGFzZXQgPSBwZC5jb25jYXQoW2lyaXNfZGF0YXNldCwgaXJpc19sYWJlbHNdLCBheGlzPTEpCiAgICAKICAgIGNvbnRleHQubG9nZ2VyLmluZm8oJ3NhdmluZyBpcmlzIGRhdGFmcmFtZSB0byB7fScuZm9ybWF0KGNvbnRleHQuYXJ0aWZhY3RfcGF0aCkpCiAgICBjb250ZXh0LmxvZ19kYXRhc2V0KCdpcmlzX2RhdGFzZXQnLCBkZj1pcmlzX2RhdGFzZXQsIGZvcm1hdD1mb3JtYXQsIGluZGV4PUZhbHNlKQoK', 'base_image': 'mlrun/mlrun', 'commands': ['pip install sklearn', 'pip install pyarrow']}}}\",\"--with_mlrun\",\"--skip\"],\"env\":[{\"name\":\"DEFAULT_DOCKER_REGISTRY\",\"value\":\"index.docker.io/falkonryml\"},{\"name\":\"MLRUN_NAMESPACE\",\"valueFrom\":{\"fieldRef\":{\"fieldPath\":\"metadata.namespace\"}}},{\"name\":\"MLRUN_ARTIFACT_PATH\",\"value\":\"/home/jovyan/demos/scikit-learn-pipeline/pipe/2536a5ff-5740-44d8-96f8-26316be0611c\"}],\"resources\":{}},\"archiveLocation\":{\"archiveLogs\":true,\"s3\":{\"endpoint\":\"minio-service.kubeflow:9000\",\"bucket\":\"mlpipeline\",\"insecure\":true,\"accessKeySecret\":{\"name\":\"mlpipeline-minio-artifact\",\"key\":\"accesskey\"},\"secretKeySecret\":{\"name\":\"mlpipeline-minio-artifact\",\"key\":\"secretkey\"},\"key\":\"artifacts/demo-training-pipeline-bn97r/demo-training-pipeline-bn97r-3933567025\"}}}"
time="2021-02-05T16:43:49Z" level=info msg="Waiting on main container"
time="2021-02-05T16:43:49Z" level=warning msg="Polling root processes (1m0s)"
time="2021-02-05T16:43:49Z" level=info msg="pid 23: &{root 4096 2147484013 {990000000 63747380757 0x2d10800} {2067 96 19 16749 0 0 0 0 4096 4096 8 {1611783965 816134965} {1611783957 990000000} {1611783957 990000000} [0 0 0]}}"
time="2021-02-05T16:43:49Z" level=info msg="Secured filehandle on /proc/23/root"
time="2021-02-05T16:43:49Z" level=info msg="containerID c1afed5dcc0e0e4224c5587dc5698e96c270a652199b4fadbdf788455e0d14e4 mapped to pid 23"
time="2021-02-05T16:43:49Z" level=info msg="pid 23: &{root 4096 2147484141 {136093600 63748140229 0x2d10800} {2097271 11666555 1 16877 0 0 0 0 4096 4096 8 {1612543429 136093600} {1612543429 136093600} {1612543429 467100230} [0 0 0]}}"
time="2021-02-05T16:43:49Z" level=info msg="Secured filehandle on /proc/23/root"
time="2021-02-05T16:43:49Z" level=info msg="pid 23: &{root 4096 2147484141 {136093600 63748140229 0x2d10800} {2097271 11666555 1 16877 0 0 0 0 4096 4096 8 {1612543429 136093600} {1612543429 136093600} {1612543429 467100230} [0 0 0]}}"
time="2021-02-05T16:43:49Z" level=info msg="pid 23: &{root 4096 2147484141 {136093600 63748140229 0x2d10800} {2097271 11666555 1 16877 0 0 0 0 4096 4096 8 {1612543429 593102754} {1612543429 136093600} {1612543429 592102734} [0 0 0]}}"
time="2021-02-05T16:43:49Z" level=info msg="pid 23: &{root 4096 2147484141 {136093600 63748140229 0x2d10800} {2097271 11666555 1 16877 0 0 0 0 4096 4096 8 {1612543429 593102754} {1612543429 136093600} {1612543429 592102734} [0 0 0]}}"
time="2021-02-05T16:43:49Z" level=info msg="pid 23: &{root 4096 2147484141 {136093600 63748140229 0x2d10800} {2097271 11666555 1 16877 0 0 0 0 4096 4096 8 {1612543429 593102754} {1612543429 136093600} {1612543429 592102734} [0 0 0]}}"
time="2021-02-05T16:43:49Z" level=info msg="pid 23: &{root 4096 2147484141 {136093600 63748140229 0x2d10800} {2097271 11666555 1 16877 0 0 0 0 4096 4096 8 {1612543429 593102754} {1612543429 136093600} {1612543429 592102734} [0 0 0]}}"
time="2021-02-05T16:43:49Z" level=info msg="pid 23: &{root 4096 2147484141 {136093600 63748140229 0x2d10800} {2097271 11666555 1 16877 0 0 0 0 4096 4096 8 {1612543429 593102754} {1612543429 136093600} {1612543429 805107001} [0 0 0]}}"
time="2021-02-05T16:43:49Z" level=info msg="pid 23: &{root 4096 2147484141 {136093600 63748140229 0x2d10800} {2097271 11666555 1 16877 0 0 0 0 4096 4096 8 {1612543429 593102754} {1612543429 136093600} {1612543429 805107001} [0 0 0]}}"
time="2021-02-05T16:43:49Z" level=info msg="pid 23: &{root 4096 2147484141 {136093600 63748140229 0x2d10800} {2097271 11666555 1 16877 0 0 0 0 4096 4096 8 {1612543429 593102754} {1612543429 136093600} {1612543429 805107001} [0 0 0]}}"
time="2021-02-05T16:43:49Z" level=info msg="pid 23: &{root 4096 2147484141 {136093600 63748140229 0x2d10800} {2097271 11666555 1 16877 0 0 0 0 4096 4096 8 {1612543429 593102754} {1612543429 136093600} {1612543429 805107001} [0 0 0]}}"
time="2021-02-05T16:43:50Z" level=info msg="pid 23: &{root 4096 2147484141 {136093600 63748140229 0x2d10800} {2097271 11666555 1 16877 0 0 0 0 4096 4096 8 {1612543429 593102754} {1612543429 136093600} {1612543429 805107001} [0 0 0]}}"
time="2021-02-05T16:43:50Z" level=info msg="pid 23: &{root 4096 2147484141 {136093600 63748140229 0x2d10800} {2097271 11666555 1 16877 0 0 0 0 4096 4096 8 {1612543429 593102754} {1612543429 136093600} {1612543429 805107001} [0 0 0]}}"
time="2021-02-05T16:43:50Z" level=info msg="pid 23: &{root 4096 2147484141 {136093600 63748140229 0x2d10800} {2097271 11666555 1 16877 0 0 0 0 4096 4096 8 {1612543429 593102754} {1612543429 136093600} {1612543429 805107001} [0 0 0]}}"
time="2021-02-05T16:43:50Z" level=info msg="pid 23: &{root 4096 2147484141 {136093600 63748140229 0x2d10800} {2097271 11666555 1 16877 0 0 0 0 4096 4096 8 {1612543429 593102754} {1612543429 136093600} {1612543429 805107001} [0 0 0]}}"
time="2021-02-05T16:43:50Z" level=info msg="pid 23: &{root 4096 2147484141 {136093600 63748140229 0x2d10800} {2097271 11666555 1 16877 0 0 0 0 4096 4096 8 {1612543429 593102754} {1612543429 136093600} {1612543429 805107001} [0 0 0]}}"
time="2021-02-05T16:43:50Z" level=info msg="main container started with container ID: c1afed5dcc0e0e4224c5587dc5698e96c270a652199b4fadbdf788455e0d14e4"
time="2021-02-05T16:43:50Z" level=info msg="Starting annotations monitor"
time="2021-02-05T16:43:50Z" level=info msg="pid 23: &{root 4096 2147484141 {136093600 63748140229 0x2d10800} {2097271 11666555 1 16877 0 0 0 0 4096 4096 8 {1612543429 593102754} {1612543429 136093600} {1612543429 805107001} [0 0 0]}}"
time="2021-02-05T16:43:50Z" level=info msg="Main pid identified as 23"
time="2021-02-05T16:43:50Z" level=info msg="Successfully secured file handle on main container root filesystem"
time="2021-02-05T16:43:50Z" level=info msg="Waiting for main pid 23 to complete"
time="2021-02-05T16:43:50Z" level=info msg="Starting deadline monitor"
time="2021-02-05T16:43:50Z" level=info msg="Stopped root processes polling due to successful securing of main root fs"
time="2021-02-05T16:44:00Z" level=info msg="/argo/podmetadata/annotations updated"
time="2021-02-05T16:44:01Z" level=info msg="Main pid 23 completed"
time="2021-02-05T16:44:01Z" level=info msg="Main container completed"
time="2021-02-05T16:44:01Z" level=info msg="Saving logs"
time="2021-02-05T16:44:01Z" level=info msg="Annotations monitor stopped"
time="2021-02-05T16:44:01Z" level=info msg="Deadline monitor stopped"
time="2021-02-05T16:44:01Z" level=info msg="S3 Save path: /tmp/argo/outputs/logs/main.log, key: artifacts/demo-training-pipeline-bn97r/demo-training-pipeline-bn97r-3933567025/main.log"
time="2021-02-05T16:44:01Z" level=info msg="Creating minio client minio-service.kubeflow:9000 using static credentials"
time="2021-02-05T16:44:01Z" level=info msg="Saving from /tmp/argo/outputs/logs/main.log to s3 (endpoint: minio-service.kubeflow:9000, bucket: mlpipeline, key: artifacts/demo-training-pipeline-bn97r/demo-training-pipeline-bn97r-3933567025/main.log)"
time="2021-02-05T16:44:01Z" level=info msg="Saving output parameters"
time="2021-02-05T16:44:01Z" level=info msg="Saving path output parameter: deploy-gen-iris-image"
time="2021-02-05T16:44:01Z" level=info msg="Copying /tmp/image from base image layer"
time="2021-02-05T16:44:01Z" level=error msg="executor error: open /tmp/image: no such file or directory"
time="2021-02-05T16:44:01Z" level=info msg="Killing sidecars"
time="2021-02-05T16:44:01Z" level=info msg="Alloc=5083 TotalAlloc=13039 Sys=71104 NumGC=4 Goroutines=14"
time="2021-02-05T16:44:01Z" level=fatal msg="open /tmp/image: no such file or directory"
```

`kubectl logs demo-training-pipeline-bn97r-3933567025 -n kubeflow main`

```
Runtime:
{'kind': 'job',
 'metadata': {'name': 'gen-iris', 'project': 'sk-project', 'tag': ''},
 'spec': {'args': [],
          'build': {'base_image': 'mlrun/mlrun',
                    'commands': ['pip install sklearn', 'pip install pyarrow'],
                    'functionSourceCode': 'IyBHZW5lcmF0ZWQgYnkgbnVjbGlvLmV4cG9ydC5OdWNsaW9FeHBvcnRlcgoKaW1wb3J0IG9zCmZyb20gc2tsZWFybi5kYXRhc2V0cyBpbXBvcnQgbG9hZF9pcmlzCmZyb20gc2tsZWFybi5tb2RlbF9zZWxlY3Rpb24gaW1wb3J0IHRyYWluX3Rlc3Rfc3BsaXQKaW1wb3J0IG51bXB5IGFzIG5wCmZyb20gc2tsZWFybi5tZXRyaWNzIGltcG9ydCBhY2N1cmFjeV9zY29yZQpmcm9tIG1scnVuLmFydGlmYWN0cyBpbXBvcnQgVGFibGVBcnRpZmFjdCwgUGxvdEFydGlmYWN0CmltcG9ydCBwYW5kYXMgYXMgcGQKCmRlZiBpcmlzX2dlbmVyYXRvcihjb250ZXh0LCBmb3JtYXQ9J2NzdicpOgogICAgaXJpcyA9IGxvYWRfaXJpcygpCiAgICBpcmlzX2RhdGFzZXQgPSBwZC5EYXRhRnJhbWUoZGF0YT1pcmlzLmRhdGEsIGNvbHVtbnM9aXJpcy5mZWF0dXJlX25hbWVzKQogICAgaXJpc19sYWJlbHMgPSBwZC5EYXRhRnJhbWUoZGF0YT1pcmlzLnRhcmdldCwgY29sdW1ucz1bJ2xhYmVsJ10pCiAgICBpcmlzX2RhdGFzZXQgPSBwZC5jb25jYXQoW2lyaXNfZGF0YXNldCwgaXJpc19sYWJlbHNdLCBheGlzPTEpCiAgICAKICAgIGNvbnRleHQubG9nZ2VyLmluZm8oJ3NhdmluZyBpcmlzIGRhdGFmcmFtZSB0byB7fScuZm9ybWF0KGNvbnRleHQuYXJ0aWZhY3RfcGF0aCkpCiAgICBjb250ZXh0LmxvZ19kYXRhc2V0KCdpcmlzX2RhdGFzZXQnLCBkZj1pcmlzX2RhdGFzZXQsIGZvcm1hdD1mb3JtYXQsIGluZGV4PUZhbHNlKQoK'},
          'command': '',
          'default_handler': '',
          'description': '',
          'entry_points': {'iris_generator': {'doc': '',
                                              'lineno': 11,
                                              'name': 'iris_generator',
                                              'outputs': [{'default': ''}],
                                              'parameters': [{'default': '',
                                                              'name': 'context'},
                                                             {'default': 'csv',
                                                              'name': 'format'}]}},
          'env': [],
          'volume_mounts': [{'mountPath': '/home/jovyan/data',
                             'name': 'pvc-55208e8c-6cf1-483f-a107-bea804c96384'}],
          'volumes': [{'name': 'pvc-55208e8c-6cf1-483f-a107-bea804c96384',
                       'persistentVolumeClaim': {'claimName': 'mlrun-kit-jupyter-pvc'}}]}}
> 2021-02-05 16:43:51,999 [info] remote deployment started
> 2021-02-05 16:43:51,999 [error] database connection is not configured
> 2021-02-05 16:43:51,999 [info] building image (.falkonryml/func-sk-project-gen-iris-latest)
FROM mlrun/mlrun:0.5.5-rc3
RUN pip install sklearn
RUN pip install pyarrow

> 2021-02-05 16:43:52,000 [info] using in-cluster config.
> 2021-02-05 16:43:52,019 [info] Pod mlrun-build-gen-iris-t2zh7 created
...
E0205 16:43:57.851534       1 aws_credentials.go:77] while getting AWS credentials NoCredentialProviders: no valid providers in chain. Deprecated.
	For verbose messaging see aws.Config.CredentialsChainVerboseErrors
error checking push permissions -- make sure you entered the correct tag name, and that you are authenticated correctly, and try again: checking push permission for "index.docker.io/falkonryml/func-sk-project-gen-iris-latest": POST https://index.docker.io/v2/falkonryml/func-sk-project-gen-iris-latest/blobs/uploads/: UNAUTHORIZED: authentication required; [map[Action:pull Class: Name:falkonryml/func-sk-project-gen-iris-latest Type:repository] map[Action:push Class: Name:falkonryml/func-sk-project-gen-iris-latest Type:repository]]
> 2021-02-05 16:43:59,926 [error] pod exited with error
> 2021-02-05 16:43:59,927 [info] build completed with failed
deploy error,  build failed!
```

_Originally posted by @Vin-itall in https://github.com/mlrun/mlrun/issues/244#issuecomment-774160009_

**Comment by Vin-itall** [comment]
Please help me out on this, I can't explore mlrun further until I get this setup correct.

**Comment by Vin-itall** [comment]
The error says `[error] database connection is not configured` 
but 
os.environ['MLRUN_DBPATH'] 
yields
'http://mlrun-kit-api:8080'.

**Comment by Vin-itall** [comment]
@yaronha can you please help me out with this setup.

**Comment by yaronha** [comment]
@Vin-itall we are planning to release 0.6 (major upgrade) next week, i believe it is more robust on that front 
seems like the DB path isnt configured in the pipeline container, not sure why, also not clear which AWS credentials its looking for, do u use AWS registry?

fyi @Hedingber @gilad-shaham

**Comment by Vin-itall** [comment]
@yaronha  Hey, no I am using a docker registry.

**Comment by Vin-itall** [comment]
@yaronha I reinstalled the mlrun-kit in kubeflow namespaces with kfp already installed in it using 
```
helm --namespace mlrun \
    install mlrun-kit \
    --wait \
    --set global.registry.url=<registry-url> \
    --set global.registry.secretName=registry-credentials \
    v3io-stable/mlrun-kit
```

Will this install the latest 0.6 release? If so, I am having the same error with 0.6 release. 
Otherwise can you please update the documentation on how to install 0.6 release.

**Comment by Hedingber** [comment]
Hi @Vin-itall, 
Sorry for jumping in late,
The AWS thing is just a warning I think,
IIUC the actual error is:
`checking push permission for "index.docker.io/falkonryml/func-sk-project-gen-iris-latest": POST https://index.docker.io/v2/falkonryml/func-sk-project-gen-iris-latest/blobs/uploads/: UNAUTHORIZED`
Can you send the exact commands you ran (without your password of course) ?

**Comment by Vin-itall** [comment]
@Hedingber  I have ran the following for installation. 

```
kubectl --namespace kubeflow create secret docker-registry registry-credentials \
    --docker-server index.docker.io/username \
    --docker-username username \
    --docker-password password
```

```
helm --namespace kubeflow \
    install mlrun-kit \
    --wait \
    --set global.registry.url=index.docker.io/username \
    --set global.registry.secretName=registry-credentials \
    v3io-stable/mlrun-kit
```
And then I am trying to run the End-to-end pipeline example.

**Comment by Hedingber** [comment]
@Vin-itall Please try to switch the `index.docker.io/username` in the first command to `https://index.docker.io/v1/` I'm pretty sure that's the root cause of your problems

**Comment by Vin-itall** [comment]
@Hedingber  I changed the URL as you suggested and redeployed mlrun.

```
error checking push permissions -- make sure you entered the correct tag name, and that you are authenticated correctly, and try again: checking push permission for "https://index.docker.io/v1/falkonryml/func-sk-project-gen-iris-latest": creating push check transport for https: failed: Get "http://https/v2/": dial tcp: lookup https on 10.43.0.10:53: no such hosthttp://https/v2/": dial tcp: lookup https on 10.43.0.10:53: no such host
```
I am still getting an error.

**Comment by Vin-itall** [comment]
I am getting a similar error while trying to run xgb_serving.ipynb when I try to deploy the function. 

```
stderr:
Error parsing reference: "https://index.docker.io/v1/falkonryml/processor-default-iris-srv:latest" is not a valid repository/tag: invalid reference format
```

**Comment by Hedingber** [comment]
@Vin-itall 
That's a different error so that's a progress 🙂 
1. Making sure you only changed the first command ? the second command should remain as is (i.e. with the `index.docker.io/username`)
2. I'm pretty sure I had this error once, and it was originated in some terminal spacing error, can you try to run the first command as one line ? like this:
`kubectl --namespace kubeflow create secret docker-registry registry-credentials --docker-server https://index.docker.io/v1/ --docker-username username --docker-password password`
3. When you say you redeploy mlrun what you mean ? to prevent failing on some components caching stuff here I would highly suggest to completely uninstall the helm chart and remove the namespace between different trials

**Comment by Vin-itall** [comment]
It sure is!

1. kubectl --namespace kubeflow create secret docker-registry registry-credentials \
    --docker-server https://index.docker.io/v1/ \
    --docker-username falkonryml \
    --docker-password "-----"

helm --namespace kubeflow \
    install mlrun-kit \
    --wait \
    --set global.registry.url=index.docker.io/v1/falkonryml \
    --set global.registry.secretName=registry-credentials \
    v3io-stable/mlrun-kit

2. Sure I'll try that out. 

3. I have been uninstalling the chart completely.

**Comment by Hedingber** [comment]
@Vin-itall 
In the second command it should be `index.docker.io/<username>` not `index.docker.io/v1/<username>`

**Comment by Vin-itall** [comment]
@Hedingber  Okay, let me try this out.

**Comment by Vin-itall** [comment]
@Hedingber Registry works completely well with pushing pulling other function images. 

Getting this for pipelines now.
```
error checking push permissions -- make sure you entered the correct tag name, and that you are authenticated correctly, and try again: checking push permission for "index.docker.io/falkonryml/func-sk-project-gen-iris-latest": POST https://index.docker.io/v2/falkonryml/func-sk-project-gen-iris-latest/blobs/uploads/: UNAUTHORIZED: authentication required; [map[Action:pull Class: Name:falkonryml/func-sk-project-gen-iris-latest Type:repository] map[Action:push Class: Name:falkonryml/func-sk-project-gen-iris-latest Type:repository]]
```


-> Create Secret

kubectl --namespace kubeflow create secret docker-registry registry-credentials --docker-server https://index.docker.io/v1/ --docker-username falkonryml --docker-password ""


-> Deploy mlrun-kit in kubeflow namespace

helm --namespace kubeflow \
    install mlrun-kit \
    --wait \
    --set global.registry.url=index.docker.io/falkonryml \
    --set global.registry.secretName=registry-credentials \
    v3io-stable/mlrun-kit

**Comment by Hedingber** [comment]
@Vin-itall 
Not sure I understand, so the problem was solved for most of the demos ? you're successfully running pipelines the build images and use them ?
Is it now a problem with a specific function in a specific pipeline of a specific demo ?
If so, which one ?

**Comment by Vin-itall** [comment]
@Hedingber 

When I am trying to run the example for deploying a function using nuclio which is xgb_serving.ipynb. I was having problems with the registry before[used a workaround which is docker logging into nuclio-dashboard pod], now it's working without a problem. 

I am having problem with running all the examples that works with pipelines. i.e sklearn-project.ipynb.

**Comment by Vin-itall** [comment]
I just checked and both my `demo-training-pipeline-59lbq-2589493228` pod and `mlrun-build-gen-iris-2gx6k` pod don't have any credential parameters in the yamls. 


mlrun-build-gen-iris-2gx6k
```
apiVersion: v1
kind: Pod
metadata:
 labels:
  mlrun/class: build
  mlrun/task-name: mlrun-build-gen-iris
 name: mlrun-build-gen-iris-2gx6k
 namespace: kubeflow
spec:
 containers:
 - args:
  - --dockerfile
  - /empty/Dockerfile
  - --context
  - /context
  - --destination
  - index.docker.io/falkonryml/func-sk-project-gen-iris-latest
  - --insecure
  image: gcr.io/kaniko-project/executor:v0.24.0
  imagePullPolicy: IfNotPresent
  name: base
  resources: {}
  terminationMessagePath: /dev/termination-log
  terminationMessagePolicy: File
  volumeMounts:
  - mountPath: /empty
   name: empty
 enableServiceLinks: true
 initContainers:
 - args:
  - sh
  - -c
  - echo ${DOCKERFILE} | base64 -d > /empty/Dockerfile
  env:
  - name: DOCKERFILE
   value: RlJPTSBtbHJ1bi9tbHJ1bjowLjUuNS1yYzMKUlVOIHBpcCBpbnN0YWxsIHNrbGVhcm4KUlVOIHBpcCBpbnN0YWxsIHB5YXJyb3cK
  image: alpine
  imagePullPolicy: Always
  name: init
  volumeMounts:
  - mountPath: /empty
   name: empty
 restartPolicy: Never
 volumes:
 - emptyDir: {}
  name: empty
```


demo-training-pipeline-59lbq-2589493228

```
spec:
 containers:
 - command:
  - argoexec
  - wait
  env:
  - name: ARGO_POD_NAME
   valueFrom:
    fieldRef:
     apiVersion: v1
     fieldPath: metadata.name
  - name: ARGO_CONTAINER_RUNTIME_EXECUTOR
   value: pns
  image: gcr.io/ml-pipeline/argoexec:v2.7.5-license-compliance
  imagePullPolicy: IfNotPresent
  name: wait
  resources: {}
  securityContext:
   capabilities:
    add:
    - SYS_PTRACE
  terminationMessagePath: /dev/termination-log
  terminationMessagePolicy: File
  volumeMounts:
  - mountPath: /argo/podmetadata
   name: podmetadata
  - mountPath: /argo/secret/mlpipeline-minio-artifact
   name: mlpipeline-minio-artifact
   readOnly: true
  - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
   name: pipeline-runner-token-grwbj
   readOnly: true
 - command:
  - python
  - -m
  - mlrun
  - build
  - --kfp
  - -r
  - '{''kind'': ''job'', ''metadata'': {''name'': ''gen-iris'', ''tag'': '''', ''project'':
   ''sk-project''}, ''spec'': {''command'': '''', ''args'': [], ''volumes'': [{''name'':
   ''pvc-f9acaa31-e4e5-4ecb-b74d-9ca6884a543e'', ''persistentVolumeClaim'': {''claimName'':
   ''mlrun-kit-jupyter-pvc''}}], ''volume_mounts'': [{''mountPath'': ''/home/jovyan/data'',
   ''name'': ''pvc-f9acaa31-e4e5-4ecb-b74d-9ca6884a543e''}], ''env'': [], ''default_handler'':
   '''', ''entry_points'': {''iris_generator'': {''name'': ''iris_generator'',
   ''doc'': '''', ''parameters'': [{''name'': ''context'', ''default'': ''''},
   {''name'': ''format'', ''default'': ''csv''}], ''outputs'': [{''default'': ''''}],
   ''lineno'': 11}}, ''description'': '''', ''build'': {''functionSourceCode'':
   ''IyBHZW5lcmF0ZWQgYnkgbnVjbGlvLmV4cG9ydC5OdWNsaW9FeHBvcnRlcgoKaW1wb3J0IG9zCmZyb20gc2tsZWFybi5kYXRhc2V0cyBpbXBvcnQgbG9hZF9pcmlzCmZyb20gc2tsZWFybi5tb2RlbF9zZWxlY3Rpb24gaW1wb3J0IHRyYWluX3Rlc3Rfc3BsaXQKaW1wb3J0IG51bXB5IGFzIG5wCmZyb20gc2tsZWFybi5tZXRyaWNzIGltcG9ydCBhY2N1cmFjeV9zY29yZQpmcm9tIG1scnVuLmFydGlmYWN0cyBpbXBvcnQgVGFibGVBcnRpZmFjdCwgUGxvdEFydGlmYWN0CmltcG9ydCBwYW5kYXMgYXMgcGQKCmRlZiBpcmlzX2dlbmVyYXRvcihjb250ZXh0LCBmb3JtYXQ9J2NzdicpOgogICAgaXJpcyA9IGxvYWRfaXJpcygpCiAgICBpcmlzX2RhdGFzZXQgPSBwZC5EYXRhRnJhbWUoZGF0YT1pcmlzLmRhdGEsIGNvbHVtbnM9aXJpcy5mZWF0dXJlX25hbWVzKQogICAgaXJpc19sYWJlbHMgPSBwZC5EYXRhRnJhbWUoZGF0YT1pcmlzLnRhcmdldCwgY29sdW1ucz1bJ2xhYmVsJ10pCiAgICBpcmlzX2RhdGFzZXQgPSBwZC5jb25jYXQoW2lyaXNfZGF0YXNldCwgaXJpc19sYWJlbHNdLCBheGlzPTEpCiAgICAKICAgIGNvbnRleHQubG9nZ2VyLmluZm8oJ3NhdmluZyBpcmlzIGRhdGFmcmFtZSB0byB7fScuZm9ybWF0KGNvbnRleHQuYXJ0aWZhY3RfcGF0aCkpCiAgICBjb250ZXh0LmxvZ19kYXRhc2V0KCdpcmlzX2RhdGFzZXQnLCBkZj1pcmlzX2RhdGFzZXQsIGZvcm1hdD1mb3JtYXQsIGluZGV4PUZhbHNlKQoK'',
   ''base_image'': ''mlrun/mlrun'', ''commands'': [''pip install sklearn'', ''pip
   install pyarrow'']}}}'
  - --with_mlrun
  - --skip
  env:
  - name: DEFAULT_DOCKER_REGISTRY
   value: index.docker.io/falkonryml
  - name: MLRUN_NAMESPACE
   valueFrom:
    fieldRef:
     apiVersion: v1
     fieldPath: metadata.namespace
  - name: MLRUN_ARTIFACT_PATH
   value: /home/jovyan/demos/scikit-learn-pipeline/pipe/4c63c0e4-55f9-463e-a3d0-f773e40140f7
  image: mlrun/mlrun:0.5.5-rc3
  imagePullPolicy: IfNotPresent
  name: main
 restartPolicy: Never
 serviceAccount: pipeline-runner
 serviceAccountName: pipeline-runner
 shareProcessNamespace: true
 terminationGracePeriodSeconds: 30
 volumes:
 - downwardAPI:
   defaultMode: 420
   items:
   - fieldRef:
     apiVersion: v1
     fieldPath: metadata.annotations
    path: annotations
  name: podmetadata
 - name: mlpipeline-minio-artifact
  secret:
   defaultMode: 420
   items:
   - key: accesskey
    path: accesskey
   - key: secretkey
    path: secretkey
   secretName: mlpipeline-minio-artifact
```

Is there some config that I am missing out on?
